# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - backendkioscolucio

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Build with dotnet
        run: dotnet build KioscoInformaticoBackend/Backend.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish KioscoInformaticoBackend/Backend.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D2A4B8CDD2B34D9B95DE432DCFB395DE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F5FA12F9C9F14931859C0F6345BCC995 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7FBEFB1A405F42B780E7362488A2D7C1 }}

      - name: Set environment variable in Azure App Service
        uses: Azure/appservice-settings@v1
        with:
          app-name: 'backendkioscolucio'
          slot-name: Production
          app-settings-json: |
            [
              {
                "name": "GOOGLE_CREDENTIALS",
                "value": "${{ secrets.GOOGLE_CREDENTIALS }}",
                "slotSetting": false
              },
              {
                "name": "ConnectionStrings__mysqlRemoto",
                "value": "${{ secrets.MYSQLREMOTO_CONNECTIONSTRING }}",
                "slotSetting": false
              }
            ]
            
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backendkioscolucio'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

          
